### ISSUE TITLE
按照demo配置了 可是typescript 只能存 无法消费，请问baseDir需要怎么重新设置

### ISSUE THREAD

**Issue by zhangweiliang111** [JohnApache/egg-kafka-node#10]

**Comment by JohnApache** [comment]
最新 **1.1.0** 版本已经支持 typescript文件格式消费了，**kafkaNode**配置里设置 **baseConsumersDir** 可以修改读取目录，不传默认 是 ./app/kafka, 使用有问题可以继续反馈
