### ISSUE TITLE
发送消息的时候不指定key，consumer如何写

### ISSUE THREAD

**Issue by svenjia** [JohnApache/egg-kafka-node#12]
发送消息的时候不指定key，consumer如何写

**Comment by svenjia** [comment]
` const m = file.match(/^(.+)Consumer.[tj]s$/);
        if (!stat.isFile() || !m) return;`
如果不指定key，岂不是收不到消息哦

**Comment by JohnApache** [comment]
这个插件模式默认就是需要传key来找到对应文件的啊， 你是遇到什么其他情况了吗

**Comment by svenjia** [comment]
@JohnApache 现在是我收不到服务器发送的消息-。-但是在kafka服务器上用
`bin/kafka-console-consumer.sh--bootstrap-server 192.168.6.20:9092 --topic resGm --from-beginning`
测过是能够收到消息

**Comment by JohnApache** [comment]
只消费消息不生产消息这种吗？那我这边要针对解决下了。 上次还有一个反过来 只生产消息不消费的情况 - -

**Comment by svenjia** [comment]
拿我的例子来说，我和我们后台服务器交互，生成消息用的topic和和我消费消息的topic是不同的，而后台服务器发送的消息不知道key，所以我这边订阅后收不到消息

**Comment by JohnApache** [comment]
明白你的意思，其实改成支持不传 key就默认为空就可以了，直接加载Consumer.js 文件，这个需要我这边测试一下，然后再发个版本

**Comment by JohnApache** [comment]
最新版本已经更新了，如果收到不传key的消息 默认读取指定topic的 Consumer.[jt]s文件，我这边测试是没问题的，如果有问题可以继续反馈

**Comment by svenjia** [comment]
@JohnApache 刚才测试了让服务器发消息的时候加个key，也能收到消息~，那我更到最新版本。3q
