### ISSUE TITLE
插件的执行顺序问题

### ISSUE THREAD

**Issue by stevenluoxiaohua** [JohnApache/egg-kafka-node#13]
我们现在自己做了一组command，用来处理kafka的返回，command是用loadToApp这种方式挂载的，现在的问题是站点刚启动，command没有挂载完，消息就来了，导致找不到对应的command

**Comment by svenjia** [comment]
@JohnApache 
我也有这个问题，当kafka服务器有未消费的消息时，在启动程序后，会马上触发消息订阅，但此时egg的一些内置对象（service）上面的方法还访问不到，所以会报错！然后插件会报错
` app.logger.error(`[egg-kafka-node] consumer consume topic: ${topic} key: ${key} value: ${value} fail!`);`
我觉得应该在app.js里加上`  app.ready(async () => {
    // 此处是你原来的逻辑代码
    if (app.config.kafkaNode) kafkaNode(app);
  });`,
agent.js其实不用处理任何逻辑，应该是所有worker进程启动完成后，再去连接kafka。

**Comment by JohnApache** [comment]
@stevenluoxiaohua  我更新了一个小版本来修复这个问题，我本地测试是ok的，你可以测试一下，还会不会有问题，如果有问题及时反馈

**Comment by JohnApache** [comment]
@svenjia 本来这个插件就是 在app ready 后才会去消费数据的， 发生找不到方法的情况是因为在agent 进程下的 ready是比正常的application ready 要更早一些，此时worker进程并没有准备好，我更新了一下代码来修复这个问题. 本地测试是ok的，你可以尝试一下还会不会有同样的问题发生，我这边会及时反馈，当然有任何建议更欢迎 pr 😄

**Comment by stevenluoxiaohua** [comment]
@JohnApache 我再追加一个问题哈，我觉得消费者的目录结构定义比较粗暴，可能实际项目本地和测试2个不同的topic，最好增加一个配置映射。

**Comment by JohnApache** [comment]
@stevenluoxiaohua 只是区分本地和测试不同的topic的话，可以根据 config.prod.js，config.dev.js 不同环境使用不同的kafka配置来实现吧. 当然如果有更好的想法或建议也可以pr 或者留言反馈😄

**Comment by stevenluoxiaohua** [comment]
@JohnApache 可能我表达有点问题，我指的是消费者的实现类（Subscription），这类文件的加载是通过topic的名字来的，名字变了，目录也要变，感觉不是很科学。

**Comment by JohnApache** [comment]
@stevenluoxiaohua 有更好的改进建议可以提供一下改进示例 或者pr😄，这种不属于bug的 ，issue我先关了
