### ISSUE TITLE
是否能增加一种Subscription Topic without Key的支持

### ISSUE THREAD

**Issue by wangwangtou** [JohnApache/egg-kafka-node#14]
# 场景描述

topic1消息定义key为UUID，每个key都不一样，
在 /app/kafka/topic1 目录下增加 Consumer.js 来处理当前topic下的所有消息

# 可能会修改的代码

```javascript
// egg-kafka-node\lib\kafka-node.js  line: 96

const Subscriber = topicSubscription.get(`${topic}:${key || ''}`);
if (!Subscriber) Subscriber = topicSubscription.get(`${topic}:`); // 有Consumer.js 则用 Consumer.js 来处理
if (!Subscriber) return consumer.resume();
```

**Comment by JohnApache** [comment]
可以考虑这么改进，后续会更新上去的

**Comment by JohnApache** [comment]
已经加上了这个特性 <https://github.com/JohnApache/egg-kafka-node/blob/74ad2584cd46207c342cda87c219fbebb546ac18/lib/kafka-node.js#L96-L98>，没有找到匹配的 KeyConsumer 的时候，会判断 本地有没有 Consumer.js, 如果有的话会使用这个来消费数据,
