### ISSUE TITLE
ts版本key不是必填项，目前约束为必传

### ISSUE THREAD

**Issue by xiaotan0305** [JohnApache/egg-kafka-node#4]
![image](https://user-images.githubusercontent.com/12965330/66916457-d482ca00-f04d-11e9-891f-e0916fd23770.png)
建议改为 key?: string

**Comment by xiaotan0305** [comment]
我们这边node端只负责生产端，现在执行tsc的时报错，目前解决方案是传了一个key的空值

**Comment by JohnApache** [comment]
我这里的key必传本来意愿是为了能找到对应的消费者，如果传空的话可能插件可能就找不到消费者了。 如果有你们这种只负责生产的情况的话，我等下改成 可选参数吧

**Comment by xiaotan0305** [comment]
好的，Thanks♪(･ω･)ﾉ
